# Generated by Django 3.2.23 on 2024-04-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
