# Generated by Django 3.2.23 on 2024-04-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularityPredictionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_file_url', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_components.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
