# Generated by Django 3.2.23 on 2024-04-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularitypredictiontask',
            name='song_cover_art_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='popularitypredictiontask',
            name='song_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
